//
// Milkyway Hierarchical Verilog Dump:
// Generated on 02/28/2017 at 14:25:23
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :aludecoder_LIB
// Cell Name    :aludecoder
// Hierarchy delimiter:'/'
// Write Command : write_verilog aludecoder.pnr.v
//


module aludecoder (funct , alu_op , op );
input  [5:0] funct ;
input  [1:0] alu_op ;
output [6:0] op ;



INVX2 U9 (.A ( funct[2] ) , .Y ( n7 ) ) ;
INVX2 U8 (.A ( funct[3] ) , .Y ( n6 ) ) ;
INVX2 U7 (.A ( n18 ) , .Y ( n5 ) ) ;
INVX2 U6 (.A ( alu_op[0] ) , .Y ( n4 ) ) ;
INVX2 U5 (.A ( n24 ) , .Y ( op[0] ) ) ;
INVX2 U4 (.A ( alu_op[1] ) , .Y ( n2 ) ) ;
INVX2 U3 (.A ( op[2] ) , .Y ( n1 ) ) ;
OAI21X1 U17 (.A ( funct[1] ) , .B ( n10 ) , .C ( n8 ) , .Y ( n14 ) ) ;
AOI22X1 U16 (.A ( n13 ) , .B ( n10 ) , .C ( funct[2] ) , .D ( n14 ) , .Y ( n12 ) ) ;
OAI22X1 U15 (.A ( alu_op[1] ) , .B ( alu_op[0] ) , .C ( n12 ) , .D ( n5 ) 
    , .Y ( op[5] ) ) ;
NAND2X1 U14 (.A ( op[0] ) , .B ( funct[1] ) , .Y ( n11 ) ) ;
OAI21X1 U13 (.A ( n10 ) , .B ( n11 ) , .C ( n1 ) , .Y ( op[6] ) ) ;
INVX2 U12 (.A ( funct[0] ) , .Y ( n10 ) ) ;
INVX2 U11 (.A ( funct[1] ) , .Y ( n9 ) ) ;
INVX2 U10 (.A ( n19 ) , .Y ( n8 ) ) ;
OAI21X1 U25 (.A ( alu_op[1] ) , .B ( n4 ) , .C ( n21 ) , .Y ( op[2] ) ) ;
OAI21X1 U24 (.A ( funct[2] ) , .B ( n10 ) , .C ( n9 ) , .Y ( n20 ) ) ;
OAI22X1 U23 (.A ( alu_op[1] ) , .B ( alu_op[0] ) , .C ( n5 ) , .D ( n20 ) 
    , .Y ( op[3] ) ) ;
NAND2X1 U22 (.A ( op[0] ) , .B ( n9 ) , .Y ( n15 ) ) ;
NOR2X1 U21 (.A ( n8 ) , .B ( n2 ) , .Y ( n17 ) ) ;
AOI21X1 U20 (.A ( n17 ) , .B ( n18 ) , .C ( op[2] ) , .Y ( n16 ) ) ;
OAI21X1 U19 (.A ( n10 ) , .B ( n15 ) , .C ( n16 ) , .Y ( op[4] ) ) ;
NOR2X1 U18 (.A ( funct[2] ) , .B ( funct[1] ) , .Y ( n13 ) ) ;
NOR2X1 U33 (.A ( funct[4] ) , .B ( alu_op[0] ) , .Y ( n25 ) ) ;
NAND2X1 U32 (.A ( n25 ) , .B ( funct[5] ) , .Y ( n23 ) ) ;
NOR2X1 U31 (.A ( n23 ) , .B ( funct[3] ) , .Y ( n18 ) ) ;
NAND3X1 U30 (.A ( n18 ) , .B ( alu_op[1] ) , .C ( funct[2] ) , .Y ( n24 ) ) ;
NOR2X1 U29 (.A ( n9 ) , .B ( funct[0] ) , .Y ( n19 ) ) ;
NOR2X1 U28 (.A ( n23 ) , .B ( n2 ) , .Y ( n22 ) ) ;
NAND3X1 U27 (.A ( n19 ) , .B ( n7 ) , .C ( n22 ) , .Y ( n21 ) ) ;
NOR2X1 U26 (.A ( n21 ) , .B ( n6 ) , .Y ( op[1] ) ) ;
endmodule


