//
// Milkyway Hierarchical Verilog Dump:
// Generated on 03/28/2017 at 14:58:00
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :mips_fsm_LIB
// Cell Name    :mips_fsm
// Hierarchy delimiter:'/'
// Write Command : write_verilog mips_fsm.pnr.v
//


module mips_fsm (op , alusrcb , pcsrc , reset , clk , irwrite , aluop , 
    regdst , regwrite , brnch , pcwrite , iord , memtoreg , alusrca , 
    memwrite );
input  [5:0] op ;
output [1:0] alusrcb ;
output [1:0] pcsrc ;
input  reset ;
input  clk ;
output [3:0] irwrite ;
output [1:0] aluop ;
output regdst ;
output regwrite ;
output brnch ;
output pcwrite ;
output iord ;
output memtoreg ;
output alusrca ;
output memwrite ;


wire [3:0] state ;

assign aluop[0] = pcsrc[0] ;
assign brnch = pcsrc[0] ;
INVX2 U4 (.A ( aluop[1] ) , .Y ( n2 ) ) ;
INVX2 U3 (.A ( n22 ) , .Y ( pcsrc[1] ) ) ;
DFFPOSX1 state_reg_1_ (.Q ( state[1] ) , .CLK ( clk ) , .D ( N34 ) ) ;
DFFPOSX1 state_reg_2_ (.Q ( state[2] ) , .CLK ( clk ) , .D ( N35 ) ) ;
DFFPOSX1 state_reg_3_ (.Q ( state[3] ) , .CLK ( clk ) , .D ( N36 ) ) ;
DFFPOSX1 state_reg_0_ (.Q ( state[0] ) , .CLK ( clk ) , .D ( n5 ) ) ;
INVX2 U12 (.A ( n31 ) , .Y ( n10 ) ) ;
INVX2 U11 (.A ( state[2] ) , .Y ( n9 ) ) ;
INVX2 U10 (.A ( state[3] ) , .Y ( n8 ) ) ;
INVX2 U9 (.A ( alusrcb[1] ) , .Y ( n7 ) ) ;
INVX2 U8 (.A ( n38 ) , .Y ( n6 ) ) ;
INVX2 U7 (.A ( n45 ) , .Y ( n5 ) ) ;
INVX2 U6 (.A ( irwrite[3] ) , .Y ( n4 ) ) ;
INVX2 U5 (.A ( memwrite ) , .Y ( n3 ) ) ;
INVX2 U20 (.A ( op[3] ) , .Y ( n18 ) ) ;
INVX2 U19 (.A ( n30 ) , .Y ( n17 ) ) ;
INVX2 U18 (.A ( op[5] ) , .Y ( n16 ) ) ;
INVX2 U17 (.A ( reset ) , .Y ( n15 ) ) ;
INVX2 U16 (.A ( n37 ) , .Y ( n14 ) ) ;
INVX2 U15 (.A ( state[0] ) , .Y ( n13 ) ) ;
INVX2 U14 (.A ( state[1] ) , .Y ( n12 ) ) ;
INVX2 U13 (.A ( n24 ) , .Y ( n11 ) ) ;
NOR2X1 U28 (.A ( n25 ) , .B ( n26 ) , .Y ( memtoreg ) ) ;
NOR2X1 U27 (.A ( n23 ) , .B ( n10 ) , .Y ( irwrite[1] ) ) ;
NOR2X1 U26 (.A ( n21 ) , .B ( n23 ) , .Y ( irwrite[2] ) ) ;
NAND3X1 U25 (.A ( state[3] ) , .B ( state[2] ) , .C ( n11 ) , .Y ( n22 ) ) ;
NAND2X1 U24 (.A ( n22 ) , .B ( n23 ) , .Y ( pcwrite ) ) ;
NOR2X1 U23 (.A ( n20 ) , .B ( n21 ) , .Y ( regdst ) ) ;
OR2X1 U22 (.A ( regdst ) , .B ( memtoreg ) , .Y ( regwrite ) ) ;
INVX2 U21 (.A ( op[2] ) , .Y ( n19 ) ) ;
OAI21X1 U36 (.A ( n28 ) , .B ( n29 ) , .C ( alusrcb[1] ) , .Y ( n27 ) ) ;
AOI21X1 U35 (.A ( n2 ) , .B ( n27 ) , .C ( reset ) , .Y ( N36 ) ) ;
NOR2X1 U34 (.A ( n20 ) , .B ( n26 ) , .Y ( pcsrc[0] ) ) ;
AOI21X1 U33 (.A ( n7 ) , .B ( n20 ) , .C ( n13 ) , .Y ( alusrca ) ) ;
OAI21X1 U32 (.A ( state[3] ) , .B ( n24 ) , .C ( n23 ) , .Y ( alusrcb[0] ) ) ;
NAND2X1 U31 (.A ( state[1] ) , .B ( n13 ) , .Y ( n21 ) ) ;
NOR2X1 U30 (.A ( n24 ) , .B ( n20 ) , .Y ( memwrite ) ) ;
OAI21X1 U29 (.A ( n25 ) , .B ( n21 ) , .C ( n3 ) , .Y ( iord ) ) ;
NOR2X1 U44 (.A ( state[1] ) , .B ( op[5] ) , .Y ( n36 ) ) ;
AOI21X1 U43 (.A ( n34 ) , .B ( n36 ) , .C ( n9 ) , .Y ( n35 ) ) ;
AOI22X1 U42 (.A ( n33 ) , .B ( n34 ) , .C ( n35 ) , .D ( n6 ) , .Y ( n32 ) ) ;
OAI21X1 U41 (.A ( reset ) , .B ( n4 ) , .C ( n32 ) , .Y ( N35 ) ) ;
NAND2X1 U40 (.A ( state[3] ) , .B ( n9 ) , .Y ( n20 ) ) ;
NOR2X1 U39 (.A ( n10 ) , .B ( n20 ) , .Y ( aluop[1] ) ) ;
OAI21X1 U38 (.A ( n13 ) , .B ( n18 ) , .C ( n19 ) , .Y ( n28 ) ) ;
NAND2X1 U37 (.A ( op[5] ) , .B ( n30 ) , .Y ( n29 ) ) ;
AOI22X1 U52 (.A ( n40 ) , .B ( n31 ) , .C ( n41 ) , .D ( n30 ) , .Y ( n39 ) ) ;
OAI21X1 U51 (.A ( n12 ) , .B ( n38 ) , .C ( n39 ) , .Y ( N34 ) ) ;
NAND2X1 U50 (.A ( state[1] ) , .B ( state[0] ) , .Y ( n26 ) ) ;
NOR2X1 U49 (.A ( n23 ) , .B ( n26 ) , .Y ( irwrite[3] ) ) ;
NAND2X1 U48 (.A ( state[2] ) , .B ( n8 ) , .Y ( n25 ) ) ;
NOR2X1 U47 (.A ( n25 ) , .B ( state[1] ) , .Y ( alusrcb[1] ) ) ;
NOR2X1 U46 (.A ( n7 ) , .B ( n37 ) , .Y ( n33 ) ) ;
NOR2X1 U45 (.A ( op[3] ) , .B ( n17 ) , .Y ( n34 ) ) ;
OAI21X1 U60 (.A ( n9 ) , .B ( n46 ) , .C ( n6 ) , .Y ( n45 ) ) ;
NOR2X1 U59 (.A ( state[2] ) , .B ( reset ) , .Y ( n40 ) ) ;
NOR2X1 U58 (.A ( n13 ) , .B ( state[1] ) , .Y ( n31 ) ) ;
NAND3X1 U57 (.A ( n19 ) , .B ( n15 ) , .C ( op[5] ) , .Y ( n37 ) ) ;
NAND3X1 U56 (.A ( n31 ) , .B ( n8 ) , .C ( n14 ) , .Y ( n42 ) ) ;
NOR2X1 U55 (.A ( op[5] ) , .B ( n9 ) , .Y ( n44 ) ) ;
NAND3X1 U54 (.A ( op[2] ) , .B ( n6 ) , .C ( n44 ) , .Y ( n43 ) ) ;
AOI21X1 U53 (.A ( n42 ) , .B ( n43 ) , .C ( op[3] ) , .Y ( n41 ) ) ;
NAND2X1 U68 (.A ( n13 ) , .B ( n12 ) , .Y ( n24 ) ) ;
NAND2X1 U67 (.A ( n9 ) , .B ( n8 ) , .Y ( n23 ) ) ;
NOR2X1 U66 (.A ( n24 ) , .B ( n23 ) , .Y ( irwrite[0] ) ) ;
AOI22X1 U65 (.A ( op[5] ) , .B ( n19 ) , .C ( n18 ) , .D ( n16 ) , .Y ( n47 ) ) ;
OR2X1 U64 (.A ( op[4] ) , .B ( op[1] ) , .Y ( n48 ) ) ;
NOR2X1 U63 (.A ( op[0] ) , .B ( n48 ) , .Y ( n30 ) ) ;
OAI21X1 U62 (.A ( n47 ) , .B ( n17 ) , .C ( n12 ) , .Y ( n46 ) ) ;
NAND3X1 U61 (.A ( n13 ) , .B ( n8 ) , .C ( n15 ) , .Y ( n38 ) ) ;
endmodule


